# Minimal sherpa-onnx: offline TTS only. Included only when WAVE_BUILD_TTS is ON.

if(TARGET sherpa-onnx-cxx-api)
    return()
endif()

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_PYTHON OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_CHECK OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_BINARY OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_PORTAUDIO OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_JNI OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_C_API ON CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_WEBSOCKET OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_GPU OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_DIRECTML OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_WASM OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_TTS ON CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_SPEAKER_DIARIZATION OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_SANITIZER OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_BUILD_C_API_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_RKNN OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_AXERA OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_AXCL OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_ASCEND_NPU OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_QNN OFF CACHE BOOL "" FORCE)
set(SHERPA_ONNX_ENABLE_SPACEMIT OFF CACHE BOOL "" FORCE)

if(WAVE_ARCH_AARCH64)
    # Pi 5 / aarch64: static ORT with MLAS NEON kernels (see platform_aarch64.cmake).
    set(SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE OFF CACHE BOOL "" FORCE)
    set(SHERPA_ONNX_LINK_LIBSTDCPP_STATICALLY ON CACHE BOOL "" FORCE)
else()
    # Desktop dev: dynamic libstdc++ speeds up linking sherpa-onnx deps.
    set(SHERPA_ONNX_LINK_LIBSTDCPP_STATICALLY OFF CACHE BOOL "" FORCE)
endif()

set(_wave_saved_cxx_standard ${CMAKE_CXX_STANDARD})
set(CMAKE_CXX_STANDARD 17)
add_subdirectory(
    "${CMAKE_SOURCE_DIR}/thirdparty/sherpa-onnx"
    "${CMAKE_BINARY_DIR}/thirdparty/sherpa-onnx"
    EXCLUDE_FROM_ALL
)
set(CMAKE_CXX_STANDARD ${_wave_saved_cxx_standard})
